from __future__ import annotations

def _verb(
    name: str,
    help_text: str,
    description: str,
    handler: str,
    flags: Sequence[str],
    *,
    family: str,
    output: OutputSpec = OUTPUT_RECORD,
    exit_codes: tuple[ExitCodeSpec, ...] = MUTATION_EXIT_CODES,
    examples: Sequence[str] = (),
) -> VerbSpec:
    return VerbSpec(
        name=name,
        help=help_text,
        description=description,
        handler=handler,
        flags=tuple(flags),
        family=family,
        output=output,
        exit_codes=exit_codes,
        examples=tuple(examples),
    )


COMMAND_SPECS: tuple[CommandSpec, ...] = (
    CommandSpec(
        name="serve",
        help="Launch the selected runner-backed ASGI runtime.",
        description="Resolve deployment, materialize a runner-qualified runtime plan, validate the selected profile, and optionally launch runtime.",
        handler="serve",
        flags=(
            "repo_root",
            "report_dir",
            "environment",
            "server",
            "host",
            "port",
            "workers",
            "uds",
            "log_level",
            "access_log",
            "proxy_headers",
            "lifespan",
            "graceful_timeout",
            "pid_file",
            "health",
            "metrics",
            "public",
            "admin",
            "rpc",
            "diagnostics",
            "require_tls",
            "enable_mtls",
            "cookies",
            "jwks_refresh_seconds",
            "dry_run",
            "check",
            "db_safe_start",
            "uvicorn_loop",
            "uvicorn_http",
            "uvicorn_ws",
            "hypercorn_worker_class",
            "hypercorn_http2",
            "tigrcorn_contract",
            "tigrcorn_mode",
        ),
        family="runtime",
        examples=(
            "tigrbl-auth serve --server uvicorn --check",
            "tigrbl-auth serve --server hypercorn --host 0.0.0.0 --port 8443",
            "tigrbl-auth serve --server tigrcorn --dry-run --format yaml",
        ),
        output=OUTPUT_RUNTIME,
        exit_codes=PORTABLE_EXIT_CODES,
    ),
    CommandSpec(
        name="verify",
        help="Run verification scopes against the repository boundary.",
        description="Execute one or more verification scopes and emit structured results.",
        handler="verify",
        flags=("repo_root", "report_dir", "scope"),
        family="governance",
        output=OUTPUT_VERIFICATION,
        exit_codes=PORTABLE_EXIT_CODES,
    ),
    CommandSpec(
        name="gate",
        help="Run release gate checks.",
        description="Run one release gate or the full ordered release gate catalog.",
        handler="gate",
        flags=("repo_root", "report_dir", "name"),
        family="governance",
        output=OUTPUT_VERIFICATION,
        exit_codes=PORTABLE_EXIT_CODES,
    ),
    CommandSpec(
        name="spec",
        help="Generate, diff, and validate public contract artifacts.",
        description="Operate on the OpenAPI and OpenRPC contract surfaces.",
        verbs=(
            _verb("generate", "Generate contract artifacts.", "Generate OpenAPI/OpenRPC artifacts for the selected deployment.", "spec.generate", ("repo_root", "kind", "report_dir"), family="contracts", output=OUTPUT_CONTRACT, exit_codes=PORTABLE_EXIT_CODES),
            _verb("validate", "Validate generated contracts.", "Validate generated contracts against repository expectations.", "spec.validate", ("repo_root", "kind", "report_dir"), family="contracts", output=OUTPUT_CONTRACT, exit_codes=PORTABLE_EXIT_CODES),
            _verb("diff", "Diff generated contracts.", "Regenerate contracts and compare them to committed artifacts.", "spec.diff", ("repo_root", "kind", "baseline_file", "report_dir"), family="contracts", output=OUTPUT_CONTRACT, exit_codes=PORTABLE_EXIT_CODES),
            _verb("report", "Write contract summary reports.", "Summarize active contract contents and profile coverage.", "spec.report", ("repo_root", "kind", "report_dir"), family="contracts", output=OUTPUT_CONTRACT, exit_codes=PORTABLE_EXIT_CODES),
        ),
        family="contracts",
    ),
    CommandSpec(
        name="claims",
        help="Lint and materialize effective claims.",
        description="Operate on the claims plane.",
        verbs=(
            _verb("lint", "Run claims lint.", "Validate declared claims against mappings and boundaries.", "claims.lint", ("repo_root", "report_dir"), family="governance", output=OUTPUT_VERIFICATION, exit_codes=PORTABLE_EXIT_CODES),
            _verb("show", "Write the effective claims manifest.", "Materialize the effective claims manifest for the active deployment.", "claims.show", ("repo_root",), family="governance", output=OUTPUT_CLAIMS, exit_codes=PORTABLE_EXIT_CODES),
            _verb("status", "Summarize the claims plane.", "Summarize declared, effective, and promotable claims.", "claims.status", ("repo_root", "report_dir"), family="governance", output=OUTPUT_CLAIMS, exit_codes=PORTABLE_EXIT_CODES),
        ),
        family="governance",
    ),
    CommandSpec(
        name="evidence",
        help="Build evidence manifests and peer profile artifacts.",
        description="Operate on Tier 3/Tier 4 evidence automation.",
        verbs=(
            _verb("bundle", "Build an evidence bundle.", "Build a release/evidence bundle filtered by the effective deployment.", "evidence.bundle", ("repo_root", "tier", "bundle_dir"), family="evidence", output=OUTPUT_RELEASE, exit_codes=PORTABLE_EXIT_CODES),
            _verb("status", "Summarize evidence readiness.", "Summarize Tier 3/Tier 4 evidence readiness.", "evidence.status", ("repo_root", "tier", "report_dir"), family="evidence", output=OUTPUT_VERIFICATION, exit_codes=PORTABLE_EXIT_CODES),
            _verb("verify", "Verify evidence and peer references.", "Run evidence/peer readiness checks.", "evidence.verify", ("repo_root", "report_dir"), family="evidence", output=OUTPUT_VERIFICATION, exit_codes=PORTABLE_EXIT_CODES),
            _verb("peer-status", "Summarize peer profile execution readiness.", "Summarize configured peer execution profiles and bundle refs.", "evidence.peer_status", ("repo_root", "report_dir"), family="evidence", output=OUTPUT_COLLECTION, exit_codes=PORTABLE_EXIT_CODES),
            _verb("peer-execute", "Materialize peer execution manifests.", "Materialize peer execution manifests for configured profiles.", "evidence.peer_execute", ("repo_root", "peer_profile", "execution_mode", "report_dir"), family="evidence", output=OUTPUT_COLLECTION, exit_codes=PORTABLE_EXIT_CODES),
        ),
        family="evidence",
    ),
    CommandSpec(
        name="doctor",
        help="Run an aggregated repository health summary.",
        description="Aggregate core verification, runtime profile, contracts, evidence, and gate status.",
        handler="doctor",
        flags=("repo_root", "report_dir"),
        family="governance",
        output=OUTPUT_VERIFICATION,
        exit_codes=PORTABLE_EXIT_CODES,
    ),
    CommandSpec(
        name="bootstrap",
        help="Bootstrap deployment artifacts and checkpoint lifecycle state.",
        description="Materialize and verify baseline bootstrap manifests for deployment or plugin installation.",
        verbs=(
            _verb("status", "Summarize bootstrap readiness.", "Summarize bootstrap readiness for the selected profile and surfaces.", "bootstrap.status", ("repo_root", "report_dir"), family="operator", output=OUTPUT_COLLECTION),
            _verb("manifest", "Write bootstrap manifests.", "Write deployment, claims, evidence, and contract manifests for the selected profile.", "bootstrap.manifest", ("repo_root", "bundle_dir"), family="operator", output=OUTPUT_RECORD),
            _verb("apply", "Apply bootstrap materialization.", "Materialize bootstrap manifests and record an applied bootstrap checkpoint.", "bootstrap.apply", ("repo_root", "bundle_dir", "yes", "dry_run", "wait", "timeout"), family="operator", output=OUTPUT_RECORD),
            _verb("verify", "Verify bootstrap artifacts.", "Verify bootstrap manifests, effective artifacts, and applied checkpoint state.", "bootstrap.verify", ("repo_root", "report_dir"), family="operator", output=OUTPUT_VERIFICATION, exit_codes=PORTABLE_EXIT_CODES),
        ),
        family="operator",
    ),
    CommandSpec(
        name="migrate",
        help="Inspect migration readiness and plans.",
        description="Migration-chain status, planning, application, and verification operators.",
        verbs=(
            _verb("status", "Show migration status.", "List migration revisions and current-to-target move status.", "migrate.status", ("repo_root", "report_dir"), family="operator", output=OUTPUT_COLLECTION),
            _verb("plan", "Emit migration plan details.", "Emit the structured migration plan and replacement order.", "migrate.plan", ("repo_root",), family="operator", output=OUTPUT_RECORD),
            _verb("apply", "Apply the migration checkpoint plan.", "Record a migration application checkpoint for the structured plan.", "migrate.apply", ("repo_root", "yes", "dry_run", "wait", "timeout"), family="operator", output=OUTPUT_RECORD),
            _verb("verify", "Verify migration artifacts.", "Run migration-plan and project-tree verification.", "migrate.verify", ("repo_root", "report_dir"), family="operator", output=OUTPUT_VERIFICATION, exit_codes=PORTABLE_EXIT_CODES),
        ),
        family="operator",
    ),
    CommandSpec(
        name="release",
        help="Build release bundles and recertification reports.",
        description="Release automation and recertification operators.",
        verbs=(
            _verb("bundle", "Build a release bundle.", "Build a release bundle containing claims, evidence, contracts, ADR index, and peer refs.", "release.bundle", ("repo_root", "bundle_dir", "artifact"), family="release", output=OUTPUT_RELEASE, exit_codes=PORTABLE_EXIT_CODES),
            _verb("sign", "Sign a release bundle.", "Create externally verifiable Ed25519 attestations for an existing release bundle.", "release.sign", ("repo_root", "bundle_dir", "signing_key"), family="release", output=OUTPUT_RELEASE, exit_codes=PORTABLE_EXIT_CODES),
            _verb("verify", "Verify a signed release bundle.", "Verify release-bundle attestations and manifest integrity for an existing signed bundle.", "release.verify", ("repo_root", "bundle_dir"), family="release", output=OUTPUT_RELEASE, exit_codes=PORTABLE_EXIT_CODES),
            _verb("status", "Summarize release bundle status.", "Summarize the current release bundle and release-gate posture.", "release.status", ("repo_root", "report_dir"), family="release", output=OUTPUT_RELEASE, exit_codes=PORTABLE_EXIT_CODES),
            _verb("recertify", "Run recertification checks.", "Re-run recertification for Tigrbl and standards-boundary changes.", "release.recertify", ("repo_root", "report_dir"), family="release", output=OUTPUT_VERIFICATION, exit_codes=PORTABLE_EXIT_CODES),
        ),
        family="release",
    ),
    CommandSpec(
        name="tenant",
        help="Manage tenant records.",
        description="Stateful durable operator-plane tenant lifecycle operators.",
        verbs=(
            _verb("create", "Create a tenant record.", "Create a durable operator-plane tenant record.", "tenant.create", ("repo_root", "id", "from_file", "set_item", "if_exists", "yes", "dry_run", "wait", "timeout"), family="admin"),
            _verb("update", "Update a tenant record.", "Update a durable operator-plane tenant record.", "tenant.update", ("repo_root", "id", "from_file", "set_item", "if_missing", "yes", "dry_run", "wait", "timeout"), family="admin"),
            _verb("delete", "Delete a tenant record.", "Delete a durable operator-plane tenant record.", "tenant.delete", ("repo_root", "id", "yes", "dry_run"), family="admin"),
            _verb("get", "Get a tenant record.", "Return a single durable operator-plane tenant record.", "tenant.get", ("repo_root", "id"), family="admin", output=OUTPUT_RECORD, exit_codes=PORTABLE_EXIT_CODES),
            _verb("list", "List tenant records.", "List durable operator-plane tenant records.", "tenant.list", ("repo_root", "filter", "limit", "offset", "sort", "status_filter"), family="admin", output=OUTPUT_COLLECTION, exit_codes=PORTABLE_EXIT_CODES),
            _verb("enable", "Enable a tenant.", "Mark a tenant record enabled.", "tenant.enable", ("repo_root", "id", "yes", "dry_run"), family="admin"),
            _verb("disable", "Disable a tenant.", "Mark a tenant record disabled.", "tenant.disable", ("repo_root", "id", "yes", "dry_run"), family="admin"),
        ),
        family="admin",
    ),
    CommandSpec(
        name="client",
        help="Manage client records.",
        description="Stateful durable operator-plane client lifecycle operators.",
        verbs=(
            _verb("create", "Create a client record.", "Create a durable operator-plane client record.", "client.create", ("repo_root", "id", "from_file", "set_item", "if_exists", "yes", "dry_run", "wait", "timeout"), family="admin"),
            _verb("update", "Update a client record.", "Update a durable operator-plane client record.", "client.update", ("repo_root", "id", "from_file", "set_item", "if_missing", "yes", "dry_run", "wait", "timeout"), family="admin"),
            _verb("delete", "Delete a client record.", "Delete a durable operator-plane client record.", "client.delete", ("repo_root", "id", "yes", "dry_run"), family="admin"),
            _verb("get", "Get a client record.", "Return a single durable operator-plane client record.", "client.get", ("repo_root", "id"), family="admin", output=OUTPUT_RECORD, exit_codes=PORTABLE_EXIT_CODES),
            _verb("list", "List client records.", "List durable operator-plane client records.", "client.list", ("repo_root", "filter", "limit", "offset", "sort", "status_filter"), family="admin", output=OUTPUT_COLLECTION, exit_codes=PORTABLE_EXIT_CODES),
            _verb("rotate-secret", "Rotate a client secret.", "Rotate durable operator-plane client secret material.", "client.rotate_secret", ("repo_root", "id", "yes", "dry_run"), family="admin"),
            _verb("enable", "Enable a client.", "Mark a client record enabled.", "client.enable", ("repo_root", "id", "yes", "dry_run"), family="admin"),
            _verb("disable", "Disable a client.", "Mark a client record disabled.", "client.disable", ("repo_root", "id", "yes", "dry_run"), family="admin"),
        ),
        family="admin",
    ),
    CommandSpec(
        name="identity",
        help="Manage identity records.",
        description="Stateful durable operator-plane identity lifecycle operators.",
        verbs=(
            _verb("create", "Create an identity record.", "Create a durable operator-plane identity record.", "identity.create", ("repo_root", "id", "from_file", "set_item", "if_exists", "yes", "dry_run", "wait", "timeout"), family="admin"),
            _verb("update", "Update an identity record.", "Update a durable operator-plane identity record.", "identity.update", ("repo_root", "id", "from_file", "set_item", "if_missing", "yes", "dry_run", "wait", "timeout"), family="admin"),
            _verb("delete", "Delete an identity record.", "Delete a durable operator-plane identity record.", "identity.delete", ("repo_root", "id", "yes", "dry_run"), family="admin"),
            _verb("get", "Get an identity record.", "Return a single durable operator-plane identity record.", "identity.get", ("repo_root", "id"), family="admin", output=OUTPUT_RECORD, exit_codes=PORTABLE_EXIT_CODES),
            _verb("list", "List identity records.", "List durable operator-plane identity records.", "identity.list", ("repo_root", "filter", "limit", "offset", "sort", "status_filter"), family="admin", output=OUTPUT_COLLECTION, exit_codes=PORTABLE_EXIT_CODES),
            _verb("set-password", "Set an identity password.", "Set or rotate a durable operator-plane identity password hash.", "identity.set_password", ("repo_root", "id", "from_file", "set_item", "yes", "dry_run"), family="admin"),
            _verb("lock", "Lock an identity.", "Mark an identity record locked.", "identity.lock", ("repo_root", "id", "yes", "dry_run"), family="admin"),
            _verb("unlock", "Unlock an identity.", "Mark an identity record unlocked.", "identity.unlock", ("repo_root", "id", "yes", "dry_run"), family="admin"),
        ),
        family="admin",
    ),
    CommandSpec(
        name="flow",
        help="Manage flow records.",
        description="Stateful durable operator-plane flow lifecycle operators.",
        verbs=(
            _verb("create", "Create a flow record.", "Create a durable operator-plane flow record.", "flow.create", ("repo_root", "id", "from_file", "set_item", "if_exists", "yes", "dry_run", "wait", "timeout"), family="admin"),
            _verb("update", "Update a flow record.", "Update a durable operator-plane flow record.", "flow.update", ("repo_root", "id", "from_file", "set_item", "if_missing", "yes", "dry_run", "wait", "timeout"), family="admin"),
            _verb("delete", "Delete a flow record.", "Delete a durable operator-plane flow record.", "flow.delete", ("repo_root", "id", "yes", "dry_run"), family="admin"),
            _verb("get", "Get a flow record.", "Return a single durable operator-plane flow record.", "flow.get", ("repo_root", "id"), family="admin", output=OUTPUT_RECORD, exit_codes=PORTABLE_EXIT_CODES),
            _verb("list", "List flow records.", "List durable operator-plane flow records.", "flow.list", ("repo_root", "filter", "limit", "offset", "sort", "status_filter"), family="admin", output=OUTPUT_COLLECTION, exit_codes=PORTABLE_EXIT_CODES),
            _verb("enable", "Enable a flow.", "Mark a flow record enabled.", "flow.enable", ("repo_root", "id", "yes", "dry_run"), family="admin"),
            _verb("disable", "Disable a flow.", "Mark a flow record disabled.", "flow.disable", ("repo_root", "id", "yes", "dry_run"), family="admin"),
        ),
        family="admin",
    ),
    CommandSpec(
        name="session",
        help="Manage session records.",
        description="Stateful durable operator-plane session control operators.",
        verbs=(
            _verb("get", "Get a session record.", "Return a single durable operator-plane session record.", "session.get", ("repo_root", "id"), family="admin", output=OUTPUT_RECORD, exit_codes=PORTABLE_EXIT_CODES),
            _verb("list", "List session records.", "List durable operator-plane session records.", "session.list", ("repo_root", "filter", "limit", "offset", "sort", "status_filter"), family="admin", output=OUTPUT_COLLECTION, exit_codes=PORTABLE_EXIT_CODES),
            _verb("revoke", "Revoke a session.", "Mark a durable operator-plane session revoked.", "session.revoke", ("repo_root", "id", "yes", "dry_run"), family="admin"),
            _verb("revoke-all", "Revoke all sessions.", "Mark all durable operator-plane sessions revoked.", "session.revoke_all", ("repo_root", "filter", "status_filter", "yes", "dry_run"), family="admin"),
        ),
        family="admin",
    ),
    CommandSpec(
        name="token",
        help="Manage token records.",
        description="Stateful durable operator-plane token control operators.",
        verbs=(
            _verb("get", "Get a token record.", "Return a single durable operator-plane token record.", "token.get", ("repo_root", "id"), family="admin", output=OUTPUT_RECORD, exit_codes=PORTABLE_EXIT_CODES),
            _verb("list", "List token records.", "List durable operator-plane token records.", "token.list", ("repo_root", "filter", "limit", "offset", "sort", "status_filter"), family="admin", output=OUTPUT_COLLECTION, exit_codes=PORTABLE_EXIT_CODES),
            _verb("introspect", "Introspect a token.", "Return active/revoked status and metadata for a token record.", "token.introspect", ("repo_root", "id"), family="admin", output=OUTPUT_RECORD, exit_codes=PORTABLE_EXIT_CODES),
            _verb("revoke", "Revoke a token.", "Mark a durable operator-plane token revoked.", "token.revoke", ("repo_root", "id", "yes", "dry_run"), family="admin"),
            _verb("exchange", "Exchange a token.", "Create a derived durable operator-plane token exchange record.", "token.exchange", ("repo_root", "id", "from_file", "set_item", "yes", "dry_run"), family="admin"),
        ),
        family="admin",
    ),
    CommandSpec(
        name="keys",
        help="Manage key lifecycle and JWKS publication.",
        description="Stateful durable operator-plane key lifecycle and JWKS publication operators.",
        verbs=(
            _verb("generate", "Generate a key record.", "Generate durable operator-plane key metadata and optional JWKS publication.", "keys.generate", ("repo_root", "id", "kid", "alg", "use", "kty", "curve", "activate", "retire_after", "publish", "yes", "dry_run"), family="admin"),
            _verb("import", "Import key material.", "Import durable operator-plane key metadata from a JSON or YAML file.", "keys.import", ("repo_root", "id", "from_file", "input_path", "activate", "publish", "yes", "dry_run"), family="admin"),
            _verb("export", "Export key material.", "Export durable operator-plane key metadata to a JSON or YAML file.", "keys.export", ("repo_root", "id", "output", "format", "include_secrets", "redact", "checksum"), family="admin", output=OUTPUT_RECORD, exit_codes=PORTABLE_EXIT_CODES),
            _verb("rotate", "Rotate active key material.", "Generate successor key metadata and retire the previous active key.", "keys.rotate", ("repo_root", "id", "kid", "alg", "use", "kty", "curve", "activate", "retire_after", "publish", "yes", "dry_run"), family="admin"),
            _verb("retire", "Retire a key.", "Mark a durable operator-plane key retired.", "keys.retire", ("repo_root", "id", "yes", "dry_run", "publish"), family="admin"),
            _verb("publish-jwks", "Publish JWKS.", "Publish the current durable operator-plane JWKS document.", "keys.publish_jwks", ("repo_root", "output", "format", "include_secrets", "redact", "checksum"), family="admin", output=OUTPUT_RECORD, exit_codes=PORTABLE_EXIT_CODES),
            _verb("get", "Get a key record.", "Return a single durable operator-plane key record.", "keys.get", ("repo_root", "id"), family="admin", output=OUTPUT_RECORD, exit_codes=PORTABLE_EXIT_CODES),
            _verb("list", "List key records.", "List durable operator-plane key records.", "keys.list", ("repo_root", "filter", "limit", "offset", "sort", "status_filter"), family="admin", output=OUTPUT_COLLECTION, exit_codes=PORTABLE_EXIT_CODES),
            _verb("delete", "Delete a key record.", "Delete a durable operator-plane key record.", "keys.delete", ("repo_root", "id", "yes", "dry_run"), family="admin"),
        ),
        family="admin",
    ),
    CommandSpec(
        name="discovery",
        help="Show, validate, publish, and diff discovery artifacts.",
        description="Discovery and metadata operators bound to repository snapshots.",
        verbs=(
            _verb("show", "Show discovery metadata.", "Show the active discovery snapshot for the selected profile.", "discovery.show", ("repo_root",), family="admin", output=OUTPUT_RECORD, exit_codes=PORTABLE_EXIT_CODES),
            _verb("validate", "Validate discovery metadata.", "Validate discovery metadata and supporting contracts.", "discovery.validate", ("repo_root", "report_dir"), family="admin", output=OUTPUT_VERIFICATION, exit_codes=PORTABLE_EXIT_CODES),
            _verb("publish", "Publish discovery metadata.", "Publish discovery metadata into a release-ready output directory.", "discovery.publish", ("repo_root", "output", "format", "checksum", "yes", "dry_run"), family="admin", output=OUTPUT_RECORD),
            _verb("diff", "Diff discovery metadata.", "Diff active discovery metadata against a provided or published baseline.", "discovery.diff", ("repo_root", "input_path", "report_dir"), family="admin", output=OUTPUT_RECORD, exit_codes=PORTABLE_EXIT_CODES),
        ),
        family="admin",
    ),
    CommandSpec(
        name="import",
        help="Validate and run import portability workflows.",
        description="Import durable operator-plane state from portable artifacts.",
        verbs=(
            _verb("validate", "Validate import input.", "Validate an import artifact without mutating state.", "import.validate", ("repo_root", "input_path", "format", "checksum", "report_dir"), family="admin", output=OUTPUT_VERIFICATION, exit_codes=PORTABLE_EXIT_CODES),
            _verb("run", "Run an import.", "Import durable operator-plane state from a portable artifact.", "import.run", ("repo_root", "input_path", "format", "checksum", "yes", "dry_run", "wait", "timeout"), family="admin"),
            _verb("status", "Show import status.", "Show the last durable operator-plane import status.", "import.status", ("repo_root",), family="admin", output=OUTPUT_RECORD, exit_codes=PORTABLE_EXIT_CODES),
        ),
        family="admin",
    ),
    CommandSpec(
        name="export",
        help="Validate and run export portability workflows.",
        description="Export durable operator-plane state into portable artifacts.",
        verbs=(
            _verb("validate", "Validate export configuration.", "Validate export configuration and current operator state.", "export.validate", ("repo_root", "output", "format", "include_secrets", "redact", "checksum", "report_dir"), family="admin", output=OUTPUT_VERIFICATION, exit_codes=PORTABLE_EXIT_CODES),
            _verb("run", "Run an export.", "Export durable operator-plane state to a portable artifact.", "export.run", ("repo_root", "output", "format", "include_secrets", "redact", "checksum", "yes", "dry_run", "wait", "timeout"), family="admin"),
            _verb("status", "Show export status.", "Show the last durable operator-plane export status.", "export.status", ("repo_root",), family="admin", output=OUTPUT_RECORD, exit_codes=PORTABLE_EXIT_CODES),
        ),
        family="admin",
    ),
)


COMMAND_FAMILY_ORDER: tuple[str, ...] = (
    "runtime",
    "governance",
    "contracts",
    "evidence",
    "operator",
    "release",
    "admin",
)

FAMILY_TITLES: dict[str, str] = {
    "runtime": "Runtime",
    "governance": "Governance and certification",
    "contracts": "Contracts and automation",
    "evidence": "Evidence and peer validation",
    "operator": "Bootstrap, migration, and operator lifecycle",
    "release": "Release certification and recertification",
    "admin": "Admin/control and resource planes",
}


def _add_argument(parser: argparse.ArgumentParser, spec: FlagSpec) -> None:
    parser.add_argument(*spec.flags, help=spec.help, **dict(spec.kwargs))


def _global_parent() -> argparse.ArgumentParser:
    parent = argparse.ArgumentParser(add_help=False)
    for key in GLOBAL_ARGUMENT_KEYS:
        _add_argument(parent, ARGUMENT_SPECS[key])
    return parent
