from __future__ import annotations
# ruff: noqa: F403,F405

from typing import Any, Final

from .schema import *

CORE_PUBLIC_CAPABILITIES: Final[tuple[dict[str, Any], ...]] = (
    {
        "capability": "device-authorization",
        "kind": "publisher",
        "surface_set": "public-rest",
        "mount_group": "device_authorization",
        "paths": ("/device_authorization",),
        "methods": ("post",),
        "flags": ("enable_rfc8628",),
        "summary": "Device authorization endpoint",
        "tags": ("oauth2",),
        "publisher_ref": "tigrbl_identity_server.device_authorization_surface:include_device_authorization_endpoint",
        "targets": ("RFC 8628", "RFC 8707"),
        "contract_visible": True,
        "discovery_visible": True,
    },
    {
        "capability": "par",
        "kind": "publisher",
        "surface_set": "public-rest",
        "mount_group": "par",
        "paths": ("/par",),
        "methods": ("post",),
        "flags": ("enable_rfc9126",),
        "summary": "Pushed authorization request endpoint",
        "tags": ("oauth2",),
        "publisher_ref": "tigrbl_identity_server.par_surface:include_par_endpoint",
        "targets": ("RFC 9126", "RFC 9101", "RFC 9396", "RFC 8707", "RFC 9700"),
        "contract_visible": True,
        "discovery_visible": True,
    },
    {
        "capability": "account-profile",
        "kind": "router",
        "surface_set": "public-rest",
        "mount_group": "my_account",
        "paths": ("/account/profile",),
        "methods": ("get", "patch"),
        "flags": (),
        "summary": "End-user profile self-service",
        "tags": ("my-account",),
        "router_ref": "tigrbl_auth_backend_app_my_account.routes:api",
        "targets": ("OIDC Core 1.0", "RFC 6265", "RFC 6750"),
        "contract_visible": True,
        "discovery_visible": False,
    },
    {
        "capability": "account-sessions",
        "kind": "router",
        "surface_set": "public-rest",
        "mount_group": "my_account",
        "paths": ("/account/sessions", "/account/sessions/{session_id}"),
        "methods": ("get", "delete"),
        "flags": (),
        "summary": "End-user session self-service",
        "tags": ("my-account",),
        "router_ref": "tigrbl_auth_backend_app_my_account.routes:api",
        "targets": ("RFC 6265", "OIDC Session Management"),
        "contract_visible": True,
        "discovery_visible": False,
    },
    {
        "capability": "account-consents",
        "kind": "router",
        "surface_set": "public-rest",
        "mount_group": "my_account",
        "paths": (
            "/account/consents",
            "/account/consents/{consent_id}",
            "/account/authorized-apps",
            "/account/authorized-apps/{client_id}",
        ),
        "methods": ("get", "delete"),
        "flags": (),
        "summary": "End-user consent and authorized-app self-service",
        "tags": ("my-account",),
        "router_ref": "tigrbl_auth_backend_app_my_account.routes:api",
        "targets": ("OIDC Core 1.0", "RFC 6749"),
        "contract_visible": True,
        "discovery_visible": False,
    },
    {
        "capability": "account-credentials",
        "kind": "router",
        "surface_set": "public-rest",
        "mount_group": "my_account",
        "paths": ("/account/password/change",),
        "methods": ("post",),
        "flags": (),
        "summary": "End-user credential self-service",
        "tags": ("my-account",),
        "router_ref": "tigrbl_auth_backend_app_my_account.routes:api",
        "targets": ("RFC 6749",),
        "contract_visible": True,
        "discovery_visible": False,
    },
    {
        "capability": "token-exchange",
        "kind": "publisher",
        "surface_set": "public-rest",
        "mount_group": "token_exchange",
        "paths": ("/token/exchange",),
        "methods": ("post",),
        "flags": ("enable_rfc8693",),
        "summary": "Token exchange endpoint",
        "tags": ("oauth2",),
        "publisher_ref": "tigrbl_identity_server.token_exchange_surface:include_token_exchange_endpoint",
        "targets": ("RFC 8693", "RFC 8705", "RFC 8707", "RFC 9068", "RFC 9449"),
        "contract_visible": True,
        "discovery_visible": False,
    },
    {
        "capability": "openid-configuration",
        "kind": "publisher",
        "surface_set": "public-rest",
        "mount_group": "openid_configuration",
        "paths": ("/.well-known/openid-configuration",),
        "methods": ("get",),
        "flags": ("enable_oidc_discovery", "enable_rfc8615"),
        "summary": "OIDC discovery document",
        "tags": (".well-known",),
        "publisher_ref": "tigrbl_identity_server.oidc_discovery_surface:include_openid_configuration",
        "artifact_name": "openid-configuration.json",
        "targets": ("OIDC Discovery 1.0", "RFC 8615", "RFC 9700"),
        "contract_visible": True,
        "discovery_visible": True,
    },
    {
        "capability": "tenant-openid-configuration",
        "kind": "publisher",
        "surface_set": "public-rest",
        "mount_group": "openid_configuration",
        "paths": ("/tenants/{tenant_slug}/.well-known/openid-configuration",),
        "methods": ("get",),
        "flags": ("enable_oidc_discovery", "enable_rfc8615"),
        "summary": "Tenant-scoped OIDC discovery document",
        "tags": (".well-known", "tenant"),
        "publisher_ref": "tigrbl_identity_server.oidc_discovery_surface:include_openid_configuration",
        "artifact_name": "tenant-openid-configuration.json",
        "targets": ("OIDC Discovery 1.0", "RFC 8615", "RFC 9700"),
        "contract_visible": True,
        "discovery_visible": True,
    },
    {
        "capability": "realm-openid-configuration",
        "kind": "publisher",
        "surface_set": "public-rest",
        "mount_group": "openid_configuration",
        "paths": ("/realms/{realm_slug}/.well-known/openid-configuration",),
        "methods": ("get",),
        "flags": ("enable_oidc_discovery", "enable_rfc8615"),
        "summary": "Realm-scoped OIDC discovery document",
        "tags": (".well-known", "realm"),
        "publisher_ref": "tigrbl_identity_server.oidc_discovery_surface:include_openid_configuration",
        "artifact_name": "realm-openid-configuration.json",
        "targets": ("OIDC Discovery 1.0", "RFC 8615", "RFC 9700"),
        "contract_visible": True,
        "discovery_visible": True,
    },
    {
        "capability": "oauth-authorization-server-metadata",
        "kind": "publisher",
        "surface_set": "public-rest",
        "mount_group": "oauth_authorization_server_metadata",
        "paths": ("/.well-known/oauth-authorization-server",),
        "methods": ("get",),
        "flags": ("enable_rfc8414", "enable_rfc8615"),
        "summary": "OAuth authorization server metadata",
        "tags": (".well-known",),
        "publisher_ref": "tigrbl_identity_server.authorization_server_metadata_surface:include_rfc8414",
        "artifact_name": "oauth-authorization-server.json",
        "targets": ("RFC 8414", "RFC 8615"),
        "contract_visible": True,
        "discovery_visible": True,
    },
    {
        "capability": "oauth-protected-resource-metadata",
        "kind": "publisher",
        "surface_set": "public-rest",
        "mount_group": "oauth_protected_resource_metadata",
        "paths": ("/.well-known/oauth-protected-resource",),
        "methods": ("get",),
        "flags": ("enable_rfc9728", "enable_rfc8615"),
        "summary": "OAuth protected resource metadata",
        "tags": (".well-known",),
        "publisher_ref": "tigrbl_identity_server.protected_resource_metadata_surface:include_rfc9728",
        "artifact_name": "oauth-protected-resource.json",
        "targets": ("RFC 9728", "RFC 8615"),
        "contract_visible": True,
        "discovery_visible": True,
    },
    {
        "capability": "jwks",
        "kind": "publisher",
        "surface_set": "public-rest",
        "mount_group": "jwks",
        "paths": ("/.well-known/jwks.json",),
        "methods": ("get",),
        "flags": ("enable_rfc7517", "enable_rfc8615"),
        "summary": "JSON Web Key Set",
        "tags": (".well-known",),
        "publisher_ref": "tigrbl_identity_server.oidc_discovery_surface:include_jwks",
        "artifact_name": "jwks.json",
        "targets": ("RFC 7517", "RFC 8615"),
        "contract_visible": True,
        "discovery_visible": True,
    },
    {
        "capability": "tenant-jwks",
        "kind": "publisher",
        "surface_set": "public-rest",
        "mount_group": "jwks",
        "paths": ("/tenants/{tenant_slug}/.well-known/jwks.json",),
        "methods": ("get",),
        "flags": ("enable_rfc7517", "enable_rfc8615"),
        "summary": "Tenant-scoped JSON Web Key Set",
        "tags": (".well-known", "tenant"),
        "publisher_ref": "tigrbl_identity_server.oidc_discovery_surface:include_jwks",
        "artifact_name": "tenant-jwks.json",
        "targets": ("RFC 7517", "RFC 8615"),
        "contract_visible": True,
        "discovery_visible": True,
    },
    {
        "capability": "realm-jwks",
        "kind": "publisher",
        "surface_set": "public-rest",
        "mount_group": "jwks",
        "paths": ("/realms/{realm_slug}/.well-known/jwks.json",),
        "methods": ("get",),
        "flags": ("enable_rfc7517", "enable_rfc8615"),
        "summary": "Realm-scoped JSON Web Key Set",
        "tags": (".well-known", "realm"),
        "publisher_ref": "tigrbl_identity_server.oidc_discovery_surface:include_jwks",
        "artifact_name": "realm-jwks.json",
        "targets": ("RFC 7517", "RFC 8615"),
        "contract_visible": True,
        "discovery_visible": True,
    },
)
