from __future__ import annotations
# ruff: noqa: F403,F405

from typing import Any, Final

from .schema import *

PROTOCOL_PUBLIC_CAPABILITIES: Final[tuple[dict[str, Any], ...]] = (
    {
        "capability": "oid4vci-credential",
        "kind": "publisher",
        "surface_set": "public-rest",
        "mount_group": "advanced_protocols",
        "paths": ("/credential",),
        "methods": ("post",),
        "flags": (),
        "summary": "OID4VCI credential endpoint",
        "tags": ("oid4vci",),
        "publisher_ref": "tigrbl_identity_server.advanced_protocols:include_advanced_protocols",
        "targets": ("OID4VCI 1.0",),
        "contract_visible": True,
        "discovery_visible": False,
    },
    {
        "capability": "oid4vp-verification",
        "kind": "publisher",
        "surface_set": "public-rest",
        "mount_group": "advanced_protocols",
        "paths": ("/presentation/verify",),
        "methods": ("post",),
        "flags": (),
        "summary": "OID4VP presentation verification endpoint",
        "tags": ("oid4vp",),
        "publisher_ref": "tigrbl_identity_server.advanced_protocols:include_advanced_protocols",
        "targets": ("OID4VP 1.0",),
        "contract_visible": True,
        "discovery_visible": False,
    },
    {
        "capability": "authzen-evaluation",
        "kind": "publisher",
        "surface_set": "public-rest",
        "mount_group": "advanced_protocols",
        "paths": ("/access/v1/evaluation",),
        "methods": ("post",),
        "flags": (),
        "summary": "AuthZEN access evaluation endpoint",
        "tags": ("authzen",),
        "publisher_ref": "tigrbl_identity_server.advanced_protocols:include_advanced_protocols",
        "targets": ("AuthZEN Authorization API 1.0",),
        "contract_visible": True,
        "discovery_visible": False,
    },
    {
        "capability": "gnap-transaction",
        "kind": "publisher",
        "surface_set": "public-rest",
        "mount_group": "advanced_protocols",
        "paths": ("/gnap/tx",),
        "methods": ("post",),
        "flags": (),
        "summary": "GNAP grant transaction endpoint",
        "tags": ("gnap",),
        "publisher_ref": "tigrbl_identity_server.advanced_protocols:include_advanced_protocols",
        "targets": ("RFC 9635",),
        "contract_visible": True,
        "discovery_visible": False,
    },
    {
        "capability": "set-receiver",
        "kind": "publisher",
        "surface_set": "public-rest",
        "mount_group": "advanced_protocols",
        "paths": ("/security-events/receive",),
        "methods": ("post",),
        "flags": (),
        "summary": "Security Event Token receiver endpoint",
        "tags": ("set",),
        "publisher_ref": "tigrbl_identity_server.advanced_protocols:include_advanced_protocols",
        "targets": ("RFC 8417",),
        "contract_visible": True,
        "discovery_visible": False,
    },
    {
        "capability": "attestation-appraisal",
        "kind": "publisher",
        "surface_set": "public-rest",
        "mount_group": "advanced_protocols",
        "paths": ("/attestations/appraise",),
        "methods": ("post",),
        "flags": (),
        "summary": "Attestation evidence appraisal endpoint",
        "tags": ("attestation",),
        "publisher_ref": "tigrbl_identity_server.advanced_protocols:include_advanced_protocols",
        "targets": ("RFC 9711", "RATS"),
        "contract_visible": True,
        "discovery_visible": False,
    },
    {
        "capability": "standards-manifest",
        "kind": "publisher",
        "surface_set": "public-rest",
        "mount_group": "standards_manifest",
        "paths": ("/standards",),
        "methods": ("get",),
        "flags": (),
        "summary": "Installed identity standards and exact revisions",
        "tags": ("standards",),
        "publisher_ref": "tigrbl_identity_server.standards_manifest:include_standards_manifest",
        "targets": (),
        "contract_visible": True,
        "discovery_visible": False,
    },
    {
        "capability": "login",
        "kind": "publisher",
        "surface_set": "public-rest",
        "mount_group": "login",
        "paths": ("/login",),
        "methods": ("post",),
        "flags": ("enable_rfc6749",),
        "summary": "Password login helper",
        "tags": ("auth",),
        "router_ref": "tigrbl_identity_storage_runtime.login:router",
        "targets": ("RFC 6749", "RFC 9068", "RFC 6265", "OIDC Session Management"),
        "contract_visible": True,
        "discovery_visible": False,
    },
    {
        "capability": "authorize",
        "kind": "publisher",
        "surface_set": "public-rest",
        "mount_group": "authorize",
        "paths": ("/authorize",),
        "methods": ("get",),
        "flags": ("enable_rfc6749", "enable_oidc_core"),
        "summary": "Authorization endpoint",
        "tags": ("oauth2", "oidc"),
        "router_ref": "tigrbl_identity_storage_runtime.authorization:router",
        "targets": (
            "RFC 6749",
            "OIDC Core 1.0",
            "RFC 8252",
            "RFC 8707",
            "RFC 9101",
            "RFC 9207",
            "RFC 9396",
            "RFC 9700",
            "RFC 6265",
            "OIDC Session Management",
        ),
        "contract_visible": True,
        "discovery_visible": False,
    },
    {
        "capability": "token",
        "kind": "router",
        "surface_set": "public-rest",
        "mount_group": "token",
        "paths": ("/token",),
        "methods": ("post",),
        "flags": ("enable_rfc6749",),
        "summary": "Token endpoint",
        "tags": ("oauth2",),
        "router_ref": "tigrbl_identity_storage.tables.token_record:api",
        "targets": ("RFC 6749", "RFC 6750", "RFC 9068", "RFC 9700"),
        "contract_visible": True,
        "discovery_visible": False,
    },
    {
        "capability": "userinfo",
        "kind": "publisher",
        "surface_set": "public-rest",
        "mount_group": "userinfo",
        "paths": ("/userinfo",),
        "methods": ("get",),
        "flags": ("enable_oidc_userinfo",),
        "summary": "OIDC UserInfo endpoint",
        "tags": ("oidc",),
        "publisher_ref": "tigrbl_identity_storage_runtime.userinfo:include_oidc_userinfo",
        "targets": ("OIDC UserInfo", "RFC 6750"),
        "contract_visible": True,
        "discovery_visible": True,
    },
    {
        "capability": "introspection",
        "kind": "publisher",
        "surface_set": "public-rest",
        "mount_group": "introspection",
        "paths": ("/introspect",),
        "methods": ("post",),
        "flags": ("enable_rfc7662",),
        "summary": "Token introspection endpoint",
        "tags": ("oauth2",),
        "publisher_ref": "tigrbl_identity_server.introspection_surface:include_introspection_endpoint",
        "targets": ("RFC 7662", "RFC 6750"),
        "contract_visible": True,
        "discovery_visible": True,
    },
    {
        "capability": "register",
        "kind": "publisher",
        "surface_set": "public-rest",
        "mount_group": "register",
        "paths": ("/register",),
        "methods": ("post",),
        "flags": ("enable_rfc7591",),
        "summary": "Dynamic client registration endpoint",
        "tags": ("oauth2",),
        "publisher_ref": "tigrbl_identity_storage_runtime.client_registration:include_client_registration_endpoint",
        "targets": ("RFC 7591", "RFC 8252", "OIDC RP-Initiated Logout"),
        "contract_visible": True,
        "discovery_visible": True,
    },
    {
        "capability": "register-management",
        "kind": "publisher",
        "surface_set": "public-rest",
        "mount_group": "register",
        "paths": ("/register/{client_id}",),
        "methods": ("get", "put", "delete"),
        "flags": ("enable_rfc7592",),
        "summary": "Dynamic client registration management endpoint",
        "tags": ("oauth2",),
        "publisher_ref": "tigrbl_identity_storage_runtime.client_registration:include_client_registration_endpoint",
        "targets": ("RFC 7592", "RFC 8252", "OIDC RP-Initiated Logout"),
        "contract_visible": True,
        "discovery_visible": False,
    },
    {
        "capability": "revoke",
        "kind": "publisher",
        "surface_set": "public-rest",
        "mount_group": "revoke",
        "paths": ("/revoke",),
        "methods": ("post",),
        "flags": ("enable_rfc7009",),
        "summary": "Token revocation endpoint",
        "tags": ("oauth2",),
        "publisher_ref": "tigrbl_identity_storage_runtime.revocation:include_revocation_endpoint",
        "targets": ("RFC 7009",),
        "contract_visible": True,
        "discovery_visible": True,
    },
    {
        "capability": "logout",
        "kind": "publisher",
        "surface_set": "public-rest",
        "mount_group": "logout",
        "paths": ("/logout",),
        "methods": ("get", "post"),
        "flags": ("enable_oidc_rp_initiated_logout",),
        "summary": "OIDC RP-initiated logout endpoint",
        "tags": ("oidc",),
        "publisher_ref": "tigrbl_identity_storage_runtime.logout:include_logout_endpoint",
        "targets": (
            "RFC 6265",
            "OIDC Session Management",
            "OIDC RP-Initiated Logout",
            "OIDC Front-Channel Logout",
            "OIDC Back-Channel Logout",
        ),
        "contract_visible": True,
        "discovery_visible": True,
    },
)
