from __future__ import annotations

from .schema import *

PUBLIC_CAPABILITIES: Final[tuple[dict[str, Any], ...]] = (
    {
        "capability": "login",
        "kind": "publisher",
        "surface_set": "public-rest",
        "mount_group": "login",
        "paths": ("/login",),
        "methods": ("post",),
        "flags": ("enable_rfc6749",),
        "summary": "Password login helper",
        "tags": ("auth",),
        "router_ref": "tigrbl_identity_storage.tables.auth_session:login_api",
        "targets": ("RFC 6749", "RFC 9068", "RFC 6265", "OIDC Session Management"),
        "contract_visible": True,
        "discovery_visible": False,
    },
    {
        "capability": "authorize",
        "kind": "publisher",
        "surface_set": "public-rest",
        "mount_group": "authorize",
        "paths": ("/authorize",),
        "methods": ("get",),
        "flags": ("enable_rfc6749", "enable_oidc_core"),
        "summary": "Authorization endpoint",
        "tags": ("oauth2", "oidc"),
        "router_ref": "tigrbl_identity_storage.tables.auth_code:api",
        "targets": (
            "RFC 6749",
            "OIDC Core 1.0",
            "RFC 8252",
            "RFC 8707",
            "RFC 9101",
            "RFC 9207",
            "RFC 9396",
            "RFC 9700",
            "RFC 6265",
            "OIDC Session Management",
        ),
        "contract_visible": True,
        "discovery_visible": False,
    },
    {
        "capability": "token",
        "kind": "router",
        "surface_set": "public-rest",
        "mount_group": "token",
        "paths": ("/token",),
        "methods": ("post",),
        "flags": ("enable_rfc6749",),
        "summary": "Token endpoint",
        "tags": ("oauth2",),
        "router_ref": "tigrbl_identity_storage.tables.token_record:api",
        "targets": ("RFC 6749", "RFC 6750", "RFC 9068", "RFC 9700"),
        "contract_visible": True,
        "discovery_visible": False,
    },
    {
        "capability": "userinfo",
        "kind": "publisher",
        "surface_set": "public-rest",
        "mount_group": "userinfo",
        "paths": ("/userinfo",),
        "methods": ("get",),
        "flags": ("enable_oidc_userinfo",),
        "summary": "OIDC UserInfo endpoint",
        "tags": ("oidc",),
        "publisher_ref": "tigrbl_identity_storage_runtime.userinfo:include_oidc_userinfo",
        "targets": ("OIDC UserInfo", "RFC 6750"),
        "contract_visible": True,
        "discovery_visible": True,
    },
    {
        "capability": "introspection",
        "kind": "publisher",
        "surface_set": "public-rest",
        "mount_group": "introspection",
        "paths": ("/introspect",),
        "methods": ("post",),
        "flags": ("enable_rfc7662",),
        "summary": "Token introspection endpoint",
        "tags": ("oauth2",),
        "publisher_ref": "tigrbl_identity_storage_runtime.introspection:include_introspection_endpoint",
        "targets": ("RFC 7662", "RFC 6750"),
        "contract_visible": True,
        "discovery_visible": True,
    },
    {
        "capability": "register",
        "kind": "publisher",
        "surface_set": "public-rest",
        "mount_group": "register",
        "paths": ("/register",),
        "methods": ("post",),
        "flags": ("enable_rfc7591",),
        "summary": "Dynamic client registration endpoint",
        "tags": ("oauth2",),
        "publisher_ref": "tigrbl_identity_storage_runtime.client_registration:include_client_registration_endpoint",
        "targets": ("RFC 7591", "RFC 8252", "OIDC RP-Initiated Logout"),
        "contract_visible": True,
        "discovery_visible": True,
    },
    {
        "capability": "register-management",
        "kind": "publisher",
        "surface_set": "public-rest",
        "mount_group": "register",
        "paths": ("/register/{client_id}",),
        "methods": ("get", "put", "delete"),
        "flags": ("enable_rfc7592",),
        "summary": "Dynamic client registration management endpoint",
        "tags": ("oauth2",),
        "publisher_ref": "tigrbl_identity_storage_runtime.client_registration:include_client_registration_endpoint",
        "targets": ("RFC 7592", "RFC 8252", "OIDC RP-Initiated Logout"),
        "contract_visible": True,
        "discovery_visible": False,
    },
    {
        "capability": "revoke",
        "kind": "publisher",
        "surface_set": "public-rest",
        "mount_group": "revoke",
        "paths": ("/revoke",),
        "methods": ("post",),
        "flags": ("enable_rfc7009",),
        "summary": "Token revocation endpoint",
        "tags": ("oauth2",),
        "publisher_ref": "tigrbl_identity_storage_runtime.revocation:include_revocation_endpoint",
        "targets": ("RFC 7009",),
        "contract_visible": True,
        "discovery_visible": True,
    },
    {
        "capability": "logout",
        "kind": "publisher",
        "surface_set": "public-rest",
        "mount_group": "logout",
        "paths": ("/logout",),
        "methods": ("get", "post"),
        "flags": ("enable_oidc_rp_initiated_logout",),
        "summary": "OIDC RP-initiated logout endpoint",
        "tags": ("oidc",),
        "publisher_ref": "tigrbl_identity_storage_runtime.logout:include_logout_endpoint",
        "targets": (
            "RFC 6265",
            "OIDC Session Management",
            "OIDC RP-Initiated Logout",
            "OIDC Front-Channel Logout",
            "OIDC Back-Channel Logout",
        ),
        "contract_visible": True,
        "discovery_visible": True,
    },
    {
        "capability": "device-authorization",
        "kind": "publisher",
        "surface_set": "public-rest",
        "mount_group": "device_authorization",
        "paths": ("/device_authorization",),
        "methods": ("post",),
        "flags": ("enable_rfc8628",),
        "summary": "Device authorization endpoint",
        "tags": ("oauth2",),
        "publisher_ref": "tigrbl_identity_storage_runtime.device_authorization:include_device_authorization_endpoint",
        "targets": ("RFC 8628", "RFC 8707"),
        "contract_visible": True,
        "discovery_visible": True,
    },
    {
        "capability": "par",
        "kind": "publisher",
        "surface_set": "public-rest",
        "mount_group": "par",
        "paths": ("/par",),
        "methods": ("post",),
        "flags": ("enable_rfc9126",),
        "summary": "Pushed authorization request endpoint",
        "tags": ("oauth2",),
        "publisher_ref": "tigrbl_identity_storage_runtime.par:include_par_endpoint",
        "targets": ("RFC 9126", "RFC 9101", "RFC 9396", "RFC 8707", "RFC 9700"),
        "contract_visible": True,
        "discovery_visible": True,
    },
    {
        "capability": "account-profile",
        "kind": "router",
        "surface_set": "public-rest",
        "mount_group": "my_account",
        "paths": ("/account/profile",),
        "methods": ("get", "patch"),
        "flags": (),
        "summary": "End-user profile self-service",
        "tags": ("my-account",),
        "router_ref": "tigrbl_identity_storage_runtime.account_surface:api",
        "targets": ("OIDC Core 1.0", "RFC 6265", "RFC 6750"),
        "contract_visible": True,
        "discovery_visible": False,
    },
    {
        "capability": "account-sessions",
        "kind": "router",
        "surface_set": "public-rest",
        "mount_group": "my_account",
        "paths": ("/account/sessions", "/account/sessions/{session_id}"),
        "methods": ("get", "delete"),
        "flags": (),
        "summary": "End-user session self-service",
        "tags": ("my-account",),
        "router_ref": "tigrbl_identity_storage_runtime.account_surface:api",
        "targets": ("RFC 6265", "OIDC Session Management"),
        "contract_visible": True,
        "discovery_visible": False,
    },
    {
        "capability": "account-consents",
        "kind": "router",
        "surface_set": "public-rest",
        "mount_group": "my_account",
        "paths": (
            "/account/consents",
            "/account/consents/{consent_id}",
            "/account/authorized-apps",
            "/account/authorized-apps/{client_id}",
        ),
        "methods": ("get", "delete"),
        "flags": (),
        "summary": "End-user consent and authorized-app self-service",
        "tags": ("my-account",),
        "router_ref": "tigrbl_identity_storage_runtime.account_surface:api",
        "targets": ("OIDC Core 1.0", "RFC 6749"),
        "contract_visible": True,
        "discovery_visible": False,
    },
    {
        "capability": "account-credentials",
        "kind": "router",
        "surface_set": "public-rest",
        "mount_group": "my_account",
        "paths": ("/account/password/change",),
        "methods": ("post",),
        "flags": (),
        "summary": "End-user credential self-service",
        "tags": ("my-account",),
        "router_ref": "tigrbl_identity_storage_runtime.account_surface:api",
        "targets": ("RFC 6749",),
        "contract_visible": True,
        "discovery_visible": False,
    },
    {
        "capability": "token-exchange",
        "kind": "publisher",
        "surface_set": "public-rest",
        "mount_group": "token_exchange",
        "paths": ("/token/exchange",),
        "methods": ("post",),
        "flags": ("enable_rfc8693",),
        "summary": "Token exchange endpoint",
        "tags": ("oauth2",),
        "publisher_ref": "tigrbl_identity_storage_runtime.token_exchange:include_token_exchange_endpoint",
        "targets": ("RFC 8693", "RFC 8705", "RFC 8707", "RFC 9068", "RFC 9449"),
        "contract_visible": True,
        "discovery_visible": False,
    },
    {
        "capability": "openid-configuration",
        "kind": "publisher",
        "surface_set": "public-rest",
        "mount_group": "openid_configuration",
        "paths": ("/.well-known/openid-configuration",),
        "methods": ("get",),
        "flags": ("enable_oidc_discovery", "enable_rfc8615"),
        "summary": "OIDC discovery document",
        "tags": (".well-known",),
        "publisher_ref": "tigrbl_identity_storage_runtime.metadata.oidc_discovery:include_openid_configuration",
        "artifact_name": "openid-configuration.json",
        "targets": ("OIDC Discovery 1.0", "RFC 8615", "RFC 9700"),
        "contract_visible": True,
        "discovery_visible": True,
    },
    {
        "capability": "tenant-openid-configuration",
        "kind": "publisher",
        "surface_set": "public-rest",
        "mount_group": "openid_configuration",
        "paths": ("/tenants/{tenant_slug}/.well-known/openid-configuration",),
        "methods": ("get",),
        "flags": ("enable_oidc_discovery", "enable_rfc8615"),
        "summary": "Tenant-scoped OIDC discovery document",
        "tags": (".well-known", "tenant"),
        "publisher_ref": "tigrbl_identity_storage_runtime.metadata.oidc_discovery:include_openid_configuration",
        "artifact_name": "tenant-openid-configuration.json",
        "targets": ("OIDC Discovery 1.0", "RFC 8615", "RFC 9700"),
        "contract_visible": True,
        "discovery_visible": True,
    },
    {
        "capability": "realm-openid-configuration",
        "kind": "publisher",
        "surface_set": "public-rest",
        "mount_group": "openid_configuration",
        "paths": ("/realms/{realm_slug}/.well-known/openid-configuration",),
        "methods": ("get",),
        "flags": ("enable_oidc_discovery", "enable_rfc8615"),
        "summary": "Realm-scoped OIDC discovery document",
        "tags": (".well-known", "realm"),
        "publisher_ref": "tigrbl_identity_storage_runtime.metadata.oidc_discovery:include_openid_configuration",
        "artifact_name": "realm-openid-configuration.json",
        "targets": ("OIDC Discovery 1.0", "RFC 8615", "RFC 9700"),
        "contract_visible": True,
        "discovery_visible": True,
    },
    {
        "capability": "oauth-authorization-server-metadata",
        "kind": "publisher",
        "surface_set": "public-rest",
        "mount_group": "oauth_authorization_server_metadata",
        "paths": ("/.well-known/oauth-authorization-server",),
        "methods": ("get",),
        "flags": ("enable_rfc8414", "enable_rfc8615"),
        "summary": "OAuth authorization server metadata",
        "tags": (".well-known",),
        "publisher_ref": "tigrbl_identity_storage_runtime.metadata.authorization_server_metadata:include_rfc8414",
        "artifact_name": "oauth-authorization-server.json",
        "targets": ("RFC 8414", "RFC 8615"),
        "contract_visible": True,
        "discovery_visible": True,
    },
    {
        "capability": "oauth-protected-resource-metadata",
        "kind": "publisher",
        "surface_set": "public-rest",
        "mount_group": "oauth_protected_resource_metadata",
        "paths": ("/.well-known/oauth-protected-resource",),
        "methods": ("get",),
        "flags": ("enable_rfc9728", "enable_rfc8615"),
        "summary": "OAuth protected resource metadata",
        "tags": (".well-known",),
        "publisher_ref": "tigrbl_identity_storage_runtime.metadata.protected_resource_metadata:include_rfc9728",
        "artifact_name": "oauth-protected-resource.json",
        "targets": ("RFC 9728", "RFC 8615"),
        "contract_visible": True,
        "discovery_visible": True,
    },
    {
        "capability": "jwks",
        "kind": "publisher",
        "surface_set": "public-rest",
        "mount_group": "jwks",
        "paths": ("/.well-known/jwks.json",),
        "methods": ("get",),
        "flags": ("enable_rfc7517", "enable_rfc8615"),
        "summary": "JSON Web Key Set",
        "tags": (".well-known",),
        "publisher_ref": "tigrbl_identity_storage_runtime.metadata.oidc_discovery:include_jwks",
        "artifact_name": "jwks.json",
        "targets": ("RFC 7517", "RFC 8615"),
        "contract_visible": True,
        "discovery_visible": True,
    },
    {
        "capability": "tenant-jwks",
        "kind": "publisher",
        "surface_set": "public-rest",
        "mount_group": "jwks",
        "paths": ("/tenants/{tenant_slug}/.well-known/jwks.json",),
        "methods": ("get",),
        "flags": ("enable_rfc7517", "enable_rfc8615"),
        "summary": "Tenant-scoped JSON Web Key Set",
        "tags": (".well-known", "tenant"),
        "publisher_ref": "tigrbl_identity_storage_runtime.metadata.oidc_discovery:include_jwks",
        "artifact_name": "tenant-jwks.json",
        "targets": ("RFC 7517", "RFC 8615"),
        "contract_visible": True,
        "discovery_visible": True,
    },
    {
        "capability": "realm-jwks",
        "kind": "publisher",
        "surface_set": "public-rest",
        "mount_group": "jwks",
        "paths": ("/realms/{realm_slug}/.well-known/jwks.json",),
        "methods": ("get",),
        "flags": ("enable_rfc7517", "enable_rfc8615"),
        "summary": "Realm-scoped JSON Web Key Set",
        "tags": (".well-known", "realm"),
        "publisher_ref": "tigrbl_identity_storage_runtime.metadata.oidc_discovery:include_jwks",
        "artifact_name": "realm-jwks.json",
        "targets": ("RFC 7517", "RFC 8615"),
        "contract_visible": True,
        "discovery_visible": True,
    },
)

