import React, { useState, useEffect } from 'react';
import { ProviderProfile, PolicyConfig, AuditEvent } from './types';
import { 
  CeremonyShell, 
  EvidenceDetailPanel, 
  PolicyEditor, 
  ProviderConfigHealth, 
  AuditLogsView 
} from './components';
import { 
  Shield, 
  Layers, 
  FileText, 
  Fingerprint, 
  Cpu, 
  Activity, 
  AlertTriangle, 
  User, 
  Clock, 
  Lock, 
  Sparkles,
  Info
} from 'lucide-react';

export default function App() {
  const [activeTab, setActiveTab] = useState<'ceremony' | 'evidence' | 'policy' | 'providers' | 'audit'>('ceremony');

  // 1. Initial Linked Authenticators
  const [linkedAuthenticators, setLinkedAuthenticators] = useState([
    {
      id: 'auth_01',
      name: 'MacBook TouchID Passkey',
      type: 'laptop',
      enrolledAt: '2026-03-10T12:00:00Z',
      lastUsedAt: '2026-07-15T08:00:00Z',
      backupEligible: true
    },
    {
      id: 'auth_02',
      name: 'Pixel 9 Secure Enclave Key',
      type: 'phone',
      enrolledAt: '2026-05-18T14:30:00Z',
      lastUsedAt: '2026-07-15T07:45:00Z',
      backupEligible: true
    },
    {
      id: 'auth_03',
      name: 'Corporate iPad Pro Agent',
      type: 'tablet',
      enrolledAt: '2026-06-01T09:15:00Z',
      lastUsedAt: '2026-07-12T11:20:00Z',
      backupEligible: false
    }
  ]);

  // 2. Initial Upstream Identity Providers
  const [providers, setProviders] = useState<ProviderProfile[]>([
    {
      id: 'prov_okta',
      name: 'Okta Enterprise Identity Hub',
      issuerUrl: 'https://auth.enterprise-idp.com',
      status: 'online',
      mappingRule: 'map_strict_fpt',
      claimsSupported: ['hw', 'user', 'uv', 'fpt'],
      freshnessLimitSeconds: 120
    },
    {
      id: 'prov_azure',
      name: 'Microsoft Entra ID Connection',
      issuerUrl: 'https://login.microsoftonline.com/tenant-id',
      status: 'online',
      mappingRule: 'infer_fpt_from_trust',
      claimsSupported: ['hw', 'user', 'uv'],
      freshnessLimitSeconds: 60
    },
    {
      id: 'prov_untrusted',
      name: 'Untrusted Shared Sandbox Provider',
      issuerUrl: 'https://sandbox.external-idp.net',
      status: 'degraded',
      mappingRule: 'untrusted_fallback_generic',
      claimsSupported: ['user', 'uv'],
      freshnessLimitSeconds: 300
    }
  ]);

  // 3. Initial Active Governance Policy Configuration
  const [policy, setPolicy] = useState<PolicyConfig>({
    requireFingerprint: true,
    allowedIssuers: ['iOS Platform Agent v2', 'Android Biometric SDK', 'Okta Enterprise Identity Hub', 'Microsoft Entra ID Connection'],
    maxAgeSeconds: 120,
    fallbackMethod: 'pin',
    rolloutPercentage: 100
  });

  // 4. Current Session Evidence (State generated by Sandbox Ceremonies)
  const [sessionEvidence, setSessionEvidence] = useState({
    isAuthenticated: true,
    hasFpt: false,
    isTrusted: false,
    detectedAmrs: ['hw', 'user', 'uv'],
    provider: 'WebAuthn Generic RP',
    authTime: new Date(Date.now() - 35000).toISOString(),
    freshnessSeconds: 35,
    uvFlag: true,
    directVsTransformed: 'none' as 'direct' | 'transformed' | 'none'
  });

  // 5. Initial Audit Logs
  const [auditLogs, setAuditLogs] = useState<AuditEvent[]>([
    {
      id: 'evt_001',
      timestamp: new Date(Date.now() - 3600000).toISOString(),
      type: 'user_login',
      status: 'approved',
      username: 'jick.68.0@gmail.com',
      detectedAmrs: ['hw', 'user', 'uv', 'fpt'],
      sourceProvider: 'iOS Platform Agent v2',
      userVerificationFlag: true,
      freshnessSeconds: 12,
      policySatisfied: true,
      auditReference: 'b5a2f8d1e9c74a03bc275468b1a5902cf67d4e39021bc8452ef3890251bc89a1',
      normalizedEvidence: {
        hasFpt: true,
        isTrusted: true,
        evidenceProvenance: 'Direct secure hardware enclave signature parsed.',
        directVsTransformed: 'direct'
      },
      redactedProvenance: {
        deviceClass: 'iPhone16,2 (iOS 18.2)',
        authChannel: 'Native App Secure Context',
        browserVersion: 'Safari Mobile 18.2',
        rawClaimsRedacted: true
      },
      description: 'Login ceremony approved. Subject verified using physical TouchID sensor certified by Apple Secure Enclave contract.'
    },
    {
      id: 'evt_002',
      timestamp: new Date(Date.now() - 7200000).toISOString(),
      type: 'transaction_stepup',
      status: 'fallback',
      username: 'finance_exec_2@company.internal',
      detectedAmrs: ['hw', 'user', 'uv'],
      sourceProvider: 'WebAuthn Generic RP',
      userVerificationFlag: true,
      freshnessSeconds: 180,
      policySatisfied: false,
      auditReference: '6d74b9e28cf14a09eb28172c9182ab39fa761c28f7311ba09bc291f098ab219d',
      normalizedEvidence: {
        hasFpt: false,
        isTrusted: false,
        evidenceProvenance: 'Standard WebAuthn User Verification only. Modality is unproven.',
        directVsTransformed: 'none'
      },
      redactedProvenance: {
        deviceClass: 'Windows Desktop Client (x86_64)',
        authChannel: 'Web browser RP interface',
        browserVersion: 'Chrome 125.0.0',
        rawClaimsRedacted: true
      },
      description: 'Transaction step-up ($12,500) redirected. Generic user verification did not satisfy strict Fingerprint AMR constraint.'
    },
    {
      id: 'evt_003',
      timestamp: new Date(Date.now() - 10800000).toISOString(),
      type: 'user_login',
      status: 'blocked',
      username: 'temp_contractor_9@company.internal',
      detectedAmrs: ['user', 'uv'],
      sourceProvider: 'Untrusted Shared Sandbox Provider',
      userVerificationFlag: true,
      freshnessSeconds: 5,
      policySatisfied: false,
      auditReference: 'e49a02fb129cd83a098bc19d821fa0c2937be19cf83a0210ebfa1a2c39d821fb',
      normalizedEvidence: {
        hasFpt: false,
        isTrusted: false,
        evidenceProvenance: 'Rejected due to untrusted provider claims transformation policy.',
        directVsTransformed: 'none'
      },
      redactedProvenance: {
        deviceClass: 'Generic Linux Client (arm64)',
        authChannel: 'Web Sandbox Redirect',
        browserVersion: 'Firefox 126.0',
        rawClaimsRedacted: true
      },
      description: 'Authentication attempt blocked. Subject provided uncertified claims from an untrusted sandbox identity gateway.'
    }
  ]);

  // Keep freshness counter updating in real-time
  useEffect(() => {
    const interval = setInterval(() => {
      setSessionEvidence(prev => {
        if (!prev.isAuthenticated) return prev;
        const diff = Math.floor((Date.now() - new Date(prev.authTime).getTime()) / 1000);
        return {
          ...prev,
          freshnessSeconds: diff > 0 ? diff : 0
        };
      });
    }, 1000);

    return () => clearInterval(interval);
  }, []);

  // Handle updates to Provider profiles
  const handleUpdateProvider = (updated: ProviderProfile) => {
    setProviders(providers.map(p => p.id === updated.id ? updated : p));
  };

  // Callback when a ceremony Sandbox user completes verification
  const handleCeremonySuccess = (evidence: {
    hasFpt: boolean;
    isTrusted: boolean;
    detectedAmrs: string[];
    provider: string;
    directVsTransformed: 'direct' | 'transformed' | 'none';
    description: string;
    outcomeStatus: 'approved' | 'blocked' | 'fallback';
  }) => {
    const authTime = new Date().toISOString();
    
    // Update active session state
    setSessionEvidence({
      isAuthenticated: true,
      hasFpt: evidence.hasFpt,
      isTrusted: evidence.isTrusted,
      detectedAmrs: evidence.detectedAmrs,
      provider: evidence.provider,
      authTime,
      freshnessSeconds: 0,
      uvFlag: evidence.detectedAmrs.includes('uv') || evidence.detectedAmrs.includes('user'),
      directVsTransformed: evidence.directVsTransformed
    });

    // Create a realistic audit log reference hash
    const randomHex = () => Math.floor((1 + Math.random()) * 0x10000).toString(16).substring(1);
    const auditReference = Array.from({length: 8}, randomHex).join('');

    // Append to Audit Ledger
    const newLog: AuditEvent = {
      id: `evt_${Date.now()}`,
      timestamp: authTime,
      type: 'sandbox_ceremony',
      status: evidence.outcomeStatus,
      username: 'jick.68.0@gmail.com', // Active User context
      detectedAmrs: evidence.detectedAmrs,
      sourceProvider: evidence.provider,
      userVerificationFlag: evidence.detectedAmrs.includes('uv'),
      freshnessSeconds: 0,
      policySatisfied: evidence.hasFpt && evidence.isTrusted,
      auditReference,
      normalizedEvidence: {
        hasFpt: evidence.hasFpt,
        isTrusted: evidence.isTrusted,
        evidenceProvenance: `${evidence.provider} completed with result mapping: ${evidence.directVsTransformed}`,
        directVsTransformed: evidence.directVsTransformed
      },
      redactedProvenance: {
        deviceClass: 'Developer Workspace Agent Simulator (Chrome)',
        authChannel: 'Vite Simulator Sandbox Sandbox',
        browserVersion: 'Chrome 126.0 (Antigravity Server Run)',
        rawClaimsRedacted: true
      },
      description: evidence.description
    };

    setAuditLogs(prev => [newLog, ...prev]);
  };

  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 font-sans flex flex-col justify-between" id="applet-viewport">
      {/* Top Professional Header Bar */}
      <header className="border-b border-slate-900 bg-slate-950/80 backdrop-blur-md sticky top-0 z-50 px-6 py-4 flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-indigo-500 to-indigo-950 flex items-center justify-center border border-indigo-500/30">
            <Fingerprint className="text-white w-6 h-6 animate-pulse" />
          </div>
          <div>
            <h1 className="text-base font-bold text-slate-100 tracking-tight" id="header-brand">Fingerprint AMR Governor</h1>
            <p className="text-3xs text-slate-500 font-mono tracking-wider uppercase mt-0.5">Biometric Evidence Validation Ledger</p>
          </div>
        </div>

        {/* User Context Info (Real Identity details) */}
        <div className="flex items-center gap-3 bg-slate-900/60 border border-slate-800 rounded-xl px-4 py-1.5 text-xs text-slate-400 font-mono">
          <div className="flex items-center gap-1.5" id="user-context-email">
            <User className="w-3.5 h-3.5 text-indigo-400" />
            <span className="text-slate-300 font-sans">jick.68.0@gmail.com</span>
          </div>
          <span className="text-slate-800">|</span>
          <div className="flex items-center gap-1.5">
            <Clock className="w-3.5 h-3.5 text-sky-400" />
            <span>UTC 15:42</span>
          </div>
        </div>
      </header>

      {/* Main Responsive Grid Panel */}
      <main className="flex-1 w-full max-w-7xl mx-auto px-6 py-8 grid grid-cols-1 lg:grid-cols-12 gap-6" id="dashboard-core">
        
        {/* Navigation Sidebar Drawer */}
        <nav className="lg:col-span-3 flex flex-row lg:flex-col gap-1 overflow-x-auto lg:overflow-visible pb-2 lg:pb-0 scrollbar-none border-b lg:border-b-0 lg:border-r border-slate-900 pr-0 lg:pr-6 h-fit" id="nav-sidebar">
          
          <button
            type="button"
            onClick={() => setActiveTab('ceremony')}
            className={`w-full text-left py-2 px-3 rounded-lg text-xs font-semibold flex items-center gap-2.5 transition whitespace-nowrap ${
              activeTab === 'ceremony'
                ? 'bg-indigo-950/40 text-indigo-200 border-l-2 border-indigo-500 font-bold'
                : 'text-slate-400 hover:bg-slate-900 hover:text-slate-200'
            }`}
          >
            <Sparkles className="w-4 h-4 text-indigo-400" />
            <span>Ceremony Sandbox</span>
          </button>

          <button
            type="button"
            onClick={() => setActiveTab('evidence')}
            className={`w-full text-left py-2 px-3 rounded-lg text-xs font-semibold flex items-center gap-2.5 transition whitespace-nowrap ${
              activeTab === 'evidence'
                ? 'bg-indigo-950/40 text-indigo-200 border-l-2 border-indigo-500 font-bold'
                : 'text-slate-400 hover:bg-slate-900 hover:text-slate-200'
            }`}
          >
            <Cpu className="w-4 h-4 text-indigo-400" />
            <span>Session & Registry</span>
          </button>

          <button
            type="button"
            onClick={() => setActiveTab('policy')}
            className={`w-full text-left py-2 px-3 rounded-lg text-xs font-semibold flex items-center gap-2.5 transition whitespace-nowrap ${
              activeTab === 'policy'
                ? 'bg-indigo-950/40 text-indigo-200 border-l-2 border-indigo-500 font-bold'
                : 'text-slate-400 hover:bg-slate-900 hover:text-slate-200'
            }`}
          >
            <Shield className="w-4 h-4 text-indigo-400" />
            <span>Governance Policies</span>
          </button>

          <button
            type="button"
            onClick={() => setActiveTab('providers')}
            className={`w-full text-left py-2 px-3 rounded-lg text-xs font-semibold flex items-center gap-2.5 transition whitespace-nowrap ${
              activeTab === 'providers'
                ? 'bg-indigo-950/40 text-indigo-200 border-l-2 border-indigo-500 font-bold'
                : 'text-slate-400 hover:bg-slate-900 hover:text-slate-200'
            }`}
          >
            <Layers className="w-4 h-4 text-indigo-400" />
            <span>Identity Federations</span>
          </button>

          <button
            type="button"
            onClick={() => setActiveTab('audit')}
            className={`w-full text-left py-2 px-3 rounded-lg text-xs font-semibold flex items-center gap-2.5 transition whitespace-nowrap ${
              activeTab === 'audit'
                ? 'bg-indigo-950/40 text-indigo-200 border-l-2 border-indigo-500 font-bold'
                : 'text-slate-400 hover:bg-slate-900 hover:text-slate-200'
            }`}
          >
            <FileText className="w-4 h-4 text-indigo-400" />
            <span>Audit Ledger</span>
          </button>

          {/* Quick Informational Notice on WebAuthn Limitation */}
          <div className="hidden lg:block mt-8 bg-slate-900/40 border border-slate-900 rounded-xl p-4 space-y-2">
            <span className="text-3xs uppercase tracking-wider text-slate-500 font-mono flex items-center gap-1">
              <Info className="w-3.5 h-3.5 text-sky-400" />
              WebAuthn Constraint
            </span>
            <p className="text-3xs text-slate-400 leading-relaxed">
              Standard WebAuthn user verification certifies that the user was verified, but does not identify the specific modality (fingerprint vs. face or passcode) as the fingerprint AMR (<code>fpt</code>). This governor implements secure protocols to bridge this diagnostic limit.
            </p>
          </div>
        </nav>

        {/* Content Viewer viewport */}
        <div className="lg:col-span-9" id="tab-viewport">
          {activeTab === 'ceremony' && (
            <CeremonyShell 
              onSuccess={handleCeremonySuccess} 
              policy={policy}
              providers={providers}
            />
          )}

          {activeTab === 'evidence' && (
            <EvidenceDetailPanel 
              sessionEvidence={sessionEvidence} 
              linkedAuthenticators={linkedAuthenticators}
              onRefreshEvidence={() => {
                setSessionEvidence(prev => ({
                  ...prev,
                  authTime: new Date().toISOString(),
                  freshnessSeconds: 0
                }));
              }}
            />
          )}

          {activeTab === 'policy' && (
            <PolicyEditor 
              policy={policy} 
              onChangePolicy={setPolicy}
              issuers={['iOS Platform Agent v2', 'Android Biometric SDK', 'Okta Enterprise Identity Hub', 'Microsoft Entra ID Connection', 'Untrusted Shared Sandbox Provider']}
            />
          )}

          {activeTab === 'providers' && (
            <ProviderConfigHealth 
              providers={providers} 
              onUpdateProvider={handleUpdateProvider}
            />
          )}

          {activeTab === 'audit' && (
            <AuditLogsView logs={auditLogs} />
          )}
        </div>
      </main>

      {/* Footer copyright notice */}
      <footer className="border-t border-slate-900 py-6 px-6 bg-slate-950 flex flex-col sm:flex-row justify-between items-center gap-4 text-xs text-slate-500" id="applet-footer">
        <p>© 2026 Fingerprint AMR Governance Engine. Secure Sovereign Biometric Protocol.</p>
        <div className="flex gap-4 font-mono text-3xs">
          <span>RP_IDENTIFIER: dev.amr.internal</span>
          <span>ORIGIN_BINDING: ENFORCED</span>
          <span>STATUS: ALL_SYSTEMS_OPERATIONAL</span>
        </div>
      </footer>
    </div>
  );
}
