"""Compatibility facade for tigrbl-authority-graph-durability."""

from tigrbl_authority_graph_durability import *
from tigrbl_authority_graph_concrete import *

AuthorityDerivationGraphTable = AuthorityGraphTable
AuthorityDerivationGraphNode = AuthorityGraphNodeTable
AuthorityDerivationGraphEdge = AuthorityGraphEdgeTable
AuthorityDerivationGraphRuntimeSpec = AuthorityGraphRuntimeSpec
AuthorityDerivationGraphNodeRuntimeSpec = AuthorityGraphNodeRuntimeSpec
AuthorityDerivationGraphEdgeRuntimeSpec = AuthorityGraphEdgeRuntimeSpec
