"""Protected artifact and possession-proof replay runtime specifications."""
from tigrbl_identity_storage.tables import PossessionProofReplay, ProtectedArtifactReference
from tigrbl_table_durability import deriveRuntimeTableSpec, makeRuntimeOperation
from tigrbl_token_durability.operations.artifacts import register_protected_artifact_reference, reserve_possession_proof_replay
ProtectedArtifactReferenceTable=ProtectedArtifactReference
PossessionProofReplayTable=PossessionProofReplay
ProtectedArtifactReferenceRuntimeSpec=deriveRuntimeTableSpec(ProtectedArtifactReferenceTable,operations=(makeRuntimeOperation(alias="register_protected_artifact_reference",handler=register_protected_artifact_reference),))
PossessionProofReplayRuntimeSpec=deriveRuntimeTableSpec(PossessionProofReplayTable,operations=(makeRuntimeOperation(alias="reserve_possession_proof_replay",handler=reserve_possession_proof_replay),))
__all__=["PossessionProofReplayRuntimeSpec","PossessionProofReplayTable","ProtectedArtifactReferenceRuntimeSpec","ProtectedArtifactReferenceTable"]