"""Principal and tenant identity models for the Tigrbl identity package suite."""

from __future__ import annotations

from .context import principal_var
from .models import (
    AuthorityRole,
    NONHUMAN_PRINCIPAL_KINDS,
    Principal,
    PrincipalKind,
    PrincipalStatus,
    SubjectAlias,
    TenantMembership,
    alias_for,
    create_admin_principal,
    create_app_principal,
    create_device_principal,
    create_machine_principal,
    create_nonhuman_principal,
    create_service_principal,
    create_user_principal,
    create_workload_principal,
    membership_for,
    new_principal_id,
)
from .service import PrincipalDirectory
from .tenant_discovery import (
    TENANT_JWKS_PATH,
    TENANT_OPENID_CONFIGURATION_PATH,
    TENANT_PUBLIC_DISCOVERY_FEATURES,
    TenantPublicDiscoveryBoundaryFeature,
    TenantTrustDomainAuthority,
    build_tenant_openid_config,
    enabled_tenant_record,
    require_tenant_issuer,
    resolve_tenant_trust_domain_authority,
    tenant_deployment,
    tenant_issuer,
    tenant_jwks_path,
    tenant_openid_configuration_path,
    tenant_public_discovery_boundary_integrity,
    tenant_public_discovery_boundary_manifest,
    tenant_trust_domain_authority_from_root_issuer,
)

__all__ = [
    "AuthorityRole",
    "NONHUMAN_PRINCIPAL_KINDS",
    "Principal",
    "PrincipalDirectory",
    "PrincipalKind",
    "PrincipalStatus",
    "SubjectAlias",
    "TENANT_JWKS_PATH",
    "TENANT_OPENID_CONFIGURATION_PATH",
    "TENANT_PUBLIC_DISCOVERY_FEATURES",
    "TenantPublicDiscoveryBoundaryFeature",
    "TenantTrustDomainAuthority",
    "TenantMembership",
    "alias_for",
    "build_tenant_openid_config",
    "create_admin_principal",
    "create_app_principal",
    "create_device_principal",
    "create_machine_principal",
    "create_nonhuman_principal",
    "create_service_principal",
    "create_user_principal",
    "create_workload_principal",
    "membership_for",
    "new_principal_id",
    "principal_var",
    "enabled_tenant_record",
    "require_tenant_issuer",
    "resolve_tenant_trust_domain_authority",
    "tenant_deployment",
    "tenant_issuer",
    "tenant_jwks_path",
    "tenant_openid_configuration_path",
    "tenant_public_discovery_boundary_integrity",
    "tenant_public_discovery_boundary_manifest",
    "tenant_trust_domain_authority_from_root_issuer",
]
