"""Workload reference and entitlement table runtime specifications."""
from tigrbl_identity_storage.tables import WorkloadCredentialEntitlement, WorkloadReferenceBinding
from tigrbl_table_durability import deriveRuntimeTableSpec, makeRuntimeOperation
from tigrbl_workload_identity_durability.operations.references import bind_workload_reference, grant_workload_credential_entitlement
WorkloadReferenceBindingTable=WorkloadReferenceBinding
WorkloadCredentialEntitlementTable=WorkloadCredentialEntitlement
WorkloadReferenceBindingRuntimeSpec=deriveRuntimeTableSpec(WorkloadReferenceBindingTable,operations=(makeRuntimeOperation(alias="bind_workload_reference",handler=bind_workload_reference),))
WorkloadCredentialEntitlementRuntimeSpec=deriveRuntimeTableSpec(WorkloadCredentialEntitlementTable,operations=(makeRuntimeOperation(alias="grant_workload_credential_entitlement",handler=grant_workload_credential_entitlement),))
__all__=["WorkloadCredentialEntitlementRuntimeSpec","WorkloadCredentialEntitlementTable","WorkloadReferenceBindingRuntimeSpec","WorkloadReferenceBindingTable"]