"""Compatibility surface for the PQC signing provider."""

from __future__ import annotations

from tigrbl_security_signing_pqc import (
    ML_DSA_65_ALG,
    PQC_JWK_KTY,
    PQC_LIBRARY_NAME,
    PQC_REQUIRED_DEPENDENCY,
    PQC_SIGNATURE_ALGS,
    PQCError,
    PQCSigningProvider,
    PQCSignatureKeyPair,
    assert_pqc_backend_available,
    b64url,
    b64url_decode,
    generate_pqc_signature_keypair,
    is_pqc_algorithm,
    normalize_pqc_algorithm,
    pqc_backend_available,
    pqc_backend_report,
    pqc_public_jwk,
    pqc_signing_jwk,
    public_key_from_pqc_jwk,
    secret_key_from_pqc_jwk,
    sign_pqc_payload,
    verify_pqc_signature,
)

__all__ = [
    "ML_DSA_65_ALG",
    "PQCError",
    "PQC_JWK_KTY",
    "PQC_LIBRARY_NAME",
    "PQC_REQUIRED_DEPENDENCY",
    "PQC_SIGNATURE_ALGS",
    "PQCSigningProvider",
    "PQCSignatureKeyPair",
    "assert_pqc_backend_available",
    "b64url",
    "b64url_decode",
    "generate_pqc_signature_keypair",
    "is_pqc_algorithm",
    "normalize_pqc_algorithm",
    "pqc_backend_available",
    "pqc_backend_report",
    "pqc_public_jwk",
    "pqc_signing_jwk",
    "public_key_from_pqc_jwk",
    "secret_key_from_pqc_jwk",
    "sign_pqc_payload",
    "verify_pqc_signature",
]
