"""Core identity primitives for the Tigrbl identity package suite."""

from __future__ import annotations

from .base64url import base64url_decode, base64url_encode
from .clock import (
    Clock,
    FrozenClock,
    SystemClock,
    parse_time,
    unix_seconds,
    utc_now,
    utc_now_iso,
)
from .entity_keys import normalize_entity, tenant_key
from .digests import digest_bytes, digest_text, sha256_text_digest, token_hash
from .constant_time import bytes_equal, text_equal
from .claims import ClaimType, ClaimValueType, RegisteredClaim
from .digests import constant_time_digest_equal, sha256_digest
from .artifacts import (
    ArtifactKind,
    AttestationKind,
    CredentialFormat,
    LifecycleStatus,
    ManifestKind,
    PresentationKind,
    TokenKind,
    VerificationOutcome,
)
from .media_types import (
    APPLICATION_CWT,
    APPLICATION_DC_SD_JWT,
    APPLICATION_EAT_CWT,
    APPLICATION_EAT_JWT,
    APPLICATION_VC,
    APPLICATION_VP,
    MediaType,
)
from .nonces import MIN_NONCE_BYTES, generate_nonce, nonce_equal, validate_nonce
from .protocol_tags import (
    PROTOCOL_TAGS,
    normalize_protocol_tag,
    normalize_protocol_tags,
)
from .uris import require_absolute_uri
from .errors import (
    IdentityAuthorizationError,
    IdentityConfigurationError,
    IdentityError,
    IdentityValidationError,
    InvalidKeyError,
    InvalidRefreshTokenError,
    InvalidTokenError,
    RefreshTokenError,
    RefreshTokenReuseError,
)
from .path_safety import safe_display_path, sanitize_local_paths
from .http import headers_from_scope, json_response, read_http_body, replay_http_body
from .jsonrpc import jsonrpc_error
from .primitives import (
    Audience,
    ClientId,
    ClientRef,
    CredentialRef,
    IdentityRef,
    WalletRef,
    WorkloadRef,
    ArtifactRef,
    CredentialId,
    IdentityId,
    TokenId,
    PresentationId,
    AttestationId,
    ManifestId,
    CertificateId,
    WalletId,
    WalletInstanceId,
    WorkloadId,
    TrustDomainId,
    CredentialTypeId,
    StatusListId,
    TransactionId,
    KeyId,
    Issuer,
    PrincipalId,
    PrincipalRef,
    RealmId,
    RealmRef,
    Scope,
    ScopeValue,
    Subject,
    TenantId,
    TenantRef,
    new_client_id,
    new_credential_id,
    new_principal_id,
    new_realm_id,
    new_tenant_id,
)
from .standards import StandardOwner, describe_owner
from .json_canonicalization import canonical_json_bytes, canonicalize
from .normalization import normal_tuple, pick_fields, row_active, row_value, str_tuple
from .patterns import matches_dotted_pattern
from .redaction import SECRET_FIELD_TOKENS, redact_sensitive_mapping
from .typing import StrUUID, uuid_str
from .versions import semver_key, version_in_range

__all__ = [
    "APPLICATION_CWT",
    "APPLICATION_DC_SD_JWT",
    "APPLICATION_EAT_CWT",
    "APPLICATION_EAT_JWT",
    "APPLICATION_VC",
    "APPLICATION_VP",
    "ArtifactKind",
    "AttestationId",
    "AttestationKind",
    "Audience",
    "Clock",
    "ClaimType",
    "ClaimValueType",
    "RegisteredClaim",
    "ClientId",
    "ClientRef",
    "CredentialRef",
    "IdentityRef",
    "WalletRef",
    "WorkloadRef",
    "ArtifactRef",
    "CredentialId",
    "CredentialFormat",
    "CredentialTypeId",
    "CertificateId",
    "FrozenClock",
    "IdentityAuthorizationError",
    "IdentityConfigurationError",
    "IdentityError",
    "IdentityValidationError",
    "InvalidKeyError",
    "InvalidRefreshTokenError",
    "InvalidTokenError",
    "Issuer",
    "IdentityId",
    "KeyId",
    "LifecycleStatus",
    "ManifestId",
    "ManifestKind",
    "MediaType",
    "MIN_NONCE_BYTES",
    "parse_time",
    "PrincipalId",
    "PrincipalRef",
    "PresentationId",
    "PresentationKind",
    "RealmId",
    "RealmRef",
    "Scope",
    "ScopeValue",
    "SECRET_FIELD_TOKENS",
    "StandardOwner",
    "StrUUID",
    "Subject",
    "SystemClock",
    "TenantId",
    "TenantRef",
    "TokenId",
    "TokenKind",
    "TransactionId",
    "TrustDomainId",
    "VerificationOutcome",
    "WalletId",
    "WalletInstanceId",
    "WorkloadId",
    "base64url_decode",
    "base64url_encode",
    "constant_time_digest_equal",
    "bytes_equal",
    "text_equal",
    "digest_bytes",
    "digest_text",
    "canonicalize",
    "canonical_json_bytes",
    "describe_owner",
    "generate_nonce",
    "headers_from_scope",
    "json_response",
    "jsonrpc_error",
    "matches_dotted_pattern",
    "normal_tuple",
    "nonce_equal",
    "normalize_protocol_tag",
    "normalize_protocol_tags",
    "normalize_entity",
    "pick_fields",
    "redact_sensitive_mapping",
    "RefreshTokenError",
    "RefreshTokenReuseError",
    "read_http_body",
    "replay_http_body",
    "row_active",
    "row_value",
    "safe_display_path",
    "sanitize_local_paths",
    "sha256_text_digest",
    "sha256_digest",
    "str_tuple",
    "new_client_id",
    "new_credential_id",
    "new_principal_id",
    "new_realm_id",
    "new_tenant_id",
    "tenant_key",
    "token_hash",
    "validate_nonce",
    "require_absolute_uri",
    "PROTOCOL_TAGS",
    "unix_seconds",
    "utc_now",
    "utc_now_iso",
    "uuid_str",
    "semver_key",
    "version_in_range",
]
