"""Key- and JWKS-oriented RPC methods."""

from __future__ import annotations

from tigrbl_auth.api.rpc.registry import RpcMethodDefinition
from tigrbl_auth.api.rpc.schemas.keys import JwksShowParams, JwksShowResult, KeyRecord, KeysListParams, KeysListResult, KeysRotateParams, KeysRotateResult
from tigrbl_auth.api.rpc.methods._shared import repo_root_from_context
from tigrbl_auth.services._operator_store import OperationContext
from tigrbl_auth.services.audit_service import list_audit_events
from tigrbl_auth.services.key_management import list_operator_keys_for_context, publish_operator_jwks_for_context, rotate_operator_key_for_context


def _rpc_context(context, command: str) -> OperationContext:
    issuer = getattr(getattr(context, 'deployment', None), 'issuer', None)
    return OperationContext(repo_root=repo_root_from_context(context), command=command, resource='keys', actor='rpc', profile=getattr(context, 'profile', None), issuer=issuer)


def _to_key_record(record: dict) -> KeyRecord:
    data = record.get('data') or {}
    return KeyRecord(
        id=str(record.get('id')),
        kind='operator-key',
        kid=data.get('kid') or str(record.get('id')),
        label=data.get('label'),
        service_id=data.get('service_id'),
        digest=data.get('digest'),
        created_at=record.get('created_at'),
        valid_from=data.get('valid_from'),
        valid_to=data.get('valid_to'),
        metadata=dict(data),
    )


async def handle_keys_list(_params: KeysListParams, context):
    result = list_operator_keys_for_context(_rpc_context(context, 'keys.list'), limit=100, offset=0)
    rows = [_to_key_record(item) for item in (result.items or [])]
    rotation_events = [item for item in list_audit_events(repo_root_from_context(context)) if item.get('target_type') == 'keys']
    return KeysListResult(key_count=len(rows), rotation_event_count=len(rotation_events), keys=rows, rotation_events=rotation_events)


async def handle_jwks_show(_params: JwksShowParams, context):
    artifact = publish_operator_jwks_for_context(_rpc_context(context, 'jwks.show'))
    jwks_path = repo_root_from_context(context) / artifact.path
    import json
    jwks = json.loads(jwks_path.read_text(encoding='utf-8')) if jwks_path.exists() else {'keys': []}
    return JwksShowResult(jwks=jwks)


async def handle_keys_rotate(params: KeysRotateParams, context):
    result = list_operator_keys_for_context(_rpc_context(context, 'keys.rotate.lookup'), limit=1, offset=0, sort='id')
    if not result.items:
        rotate_result = publish_operator_jwks_for_context(_rpc_context(context, 'jwks.bootstrap'))
        _ = rotate_result
        # no key to rotate; create a placeholder by publishing current state and report not-found
        from tigrbl_auth.services.key_management import generate_operator_key_for_context
        created = generate_operator_key_for_context(_rpc_context(context, 'keys.rotate.seed'), patch={'label': 'rpc-rotation-seed', 'status': 'active', 'enabled': True})
        target_id = created.record['id']
    else:
        target_id = str(result.items[0]['id'])
    rotate = rotate_operator_key_for_context(_rpc_context(context, 'keys.rotate'), record_id=target_id)
    return KeysRotateResult(status='rotated', new_kid=str((rotate.record or {}).get('id', target_id)), rotation_event={'reason': params.reason, 'result': rotate.to_payload()})


METHODS = (
    RpcMethodDefinition(
        name='keys.list',
        summary='List durable service keys and key-rotation history.',
        description='Returns key rows and key-rotation audit rows from the shared operator service layer.',
        params_model=KeysListParams,
        result_model=KeysListResult,
        handler=handle_keys_list,
        owner_module='tigrbl_auth/api/rpc/methods/keys.py',
        tags=('keys', 'jwks'),
    ),
    RpcMethodDefinition(
        name='jwks.show',
        summary='Show the effective JWKS document.',
        description='Returns the effective JWKS publication payload generated by the shared service layer.',
        params_model=JwksShowParams,
        result_model=JwksShowResult,
        handler=handle_jwks_show,
        owner_module='tigrbl_auth/api/rpc/methods/keys.py',
        tags=('keys', 'jwks'),
    ),
    RpcMethodDefinition(
        name='keys.rotate',
        summary='Rotate the signing key and persist a key-rotation event.',
        description='Performs an operator key rotation through the same service layer used by the CLI surface.',
        params_model=KeysRotateParams,
        result_model=KeysRotateResult,
        handler=handle_keys_rotate,
        owner_module='tigrbl_auth/api/rpc/methods/keys.py',
        tags=('keys', 'jwks'),
    ),
)
